# Generated by Django 5.2.5 on 2025-09-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetemplate',
            name='css_content',
        ),
        migrations.RemoveField(
            model_name='resumetemplate',
            name='html_content',
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='file_name',
            field=models.CharField(default='resumes/default.html', max_length=255),
        ),
    ]
