# Generated by Django 5.2.5 on 2025-09-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_resumetemplate_css_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresume',
            name='content',
        ),
        migrations.AddField(
            model_name='userresume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userresume',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userresume',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userresume',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
