# Generated by Django 5.2.6 on 2025-09-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_userresume_content_userresume_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresume',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='resumetemplate',
            name='file_name',
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='template_file',
            field=models.CharField(default='resumes/default.html', help_text='Path to the HTML file for this resume template', max_length=255),
        ),
        migrations.AddField(
            model_name='userresume',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='conference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='publication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='tech_stack',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
