# Generated by Django 5.2.6 on 2025-09-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresume',
            name='title',
        ),
    ]
