# Generated by Django 5.2.6 on 2025-09-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_userresume_address_alter_userresume_awards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresume',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
